name: Push branch to website

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to the main branch

jobs:
  update-base-href:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Push changes to website branch
      run: |
        git push origin website --force
